### ISSUE TITLE
Can I hook functions to the save options button/action?

### ISSUE THREAD

**Issue by Gyroscopic** [tareq1988/wordpress-settings-api-class#13]
I am using your class to specify some custom css. To invoke the changes I am creating a static css file on the server with the new css rules. This file will be enqueued when the theme is loaded.

However my dilemma is how I fire the function to create the css file? Preferably I would only like to do this when I save an options screen, but I dont know the best way to do this.

Should I modify the class to call my css build function or can I somehow hook the function to when the options are updated/saved? Or is there a better way to do this?

Any thoughts are appreciated :)

**Comment by rosell-dk** [comment]
Looking in `options.php`, I see that custom options are saved with `update_option( $option, $value );`. That means you can use the `updated_option` action hook, like this: ```add_action('updated_option', function($option_name, $old_value, $value) {...}```
