### ISSUE TITLE
Save setting defaults on `add_option`

### ISSUE THREAD

**Issue by terminalpixel** [tareq1988/wordpress-settings-api-class#22]
Hi there,

Not sure if this should be included or deliberately left out but personally I think when you give a field a default value it should be passed to the `add_option` call so that it is saved in the database as soon as the class is called.

**Comment by factmaven** [comment]
I was having this issue, but the commit that that @szepeviktor provided ([#27](https://github.com/tareq1988/wordpress-settings-api-class/pull/27)) was easy enough to add and resolve. How come this was labeled as `wontfix` @tareq1988?

**Comment by tareq1988** [comment]
The reason behind this is to not update the database unless the **Save Changes** button was clicked. You should always call for the field option with a default value. 

For Example:
```php
/**
 * Get the value of a settings field
 *
 * @param string $option settings field name
 * @param string $section the section name this field belongs to
 * @param string $default default text if it's not found
 * @return mixed
 */
function my_get_option( $option, $section, $default = '' ) {

    $options = get_option( $section );

    if ( isset( $options[$option] ) ) {
        return $options[$option];
    }

    return $default;
}```

When you are retrieving a value of the `test_option` of the section `test_section` and expecting something, pass a default value.
`$value = my_get_option( 'test_option', 'test_section', 'your_default_value_here' );`

**Comment by factmaven** [comment]
What do you mean by:

> You should always call for the field option with a default value.

For me, I want the default options saved in the database when the plugin is first installed. Then, allow the user to toggle the settings. if they do not want the default options.
