### ISSUE TITLE
Multicheck field giving me a warning 

### ISSUE THREAD

**Issue by wpbean** [tareq1988/wordpress-settings-api-class#33]
Hi, 
I am trying to use the multicheck filed, it's working fine, But problem is if I check nothing form multicheck and click save change button it's giving me a warning of invalid argument supplied for foreach in setting api php class 386 line. 
It's not giving me warning if WP_DEBUG if false.  

Thanks 
Imran Khan

**Comment by tareq1988** [comment]
Can you try the latest version of the settings api and regenerate the issue? I didn't find any error like this.
