### ISSUE TITLE
Set the default value for multicheck

### ISSUE THREAD

**Issue by hyyan** [tareq1988/wordpress-settings-api-class#50]
@tareq1988 thanks for the great work ,

I have tried to set the default value for mutlicheck field like this 

```php
$metas = array(....);
$fields['my-section-name'] = array();
foreach ($metas as $section => $values) {

$fields['my-section-name'][] = array(
        'name' => $section,
        'label' => $section,
        'type' => 'multicheck',
        'default' => array_flip($values),
        'options' => array_combine(
                $values
                , $values
        )
    );
}
```
The checkboxes are displayed correctly , but the default array is ignored , after some digging I found this in following line : https://github.com/tareq1988/wordpress-settings-api-class/blob/master/src/class.settings-api.php#L234

I think it must be something like this : 

```php
$checked = isset( $value[$key] ) ? $key : '0';
```

Maybe I am doing it the wrong way ? Should I send PR for this ?

**Comment by roidayan** [comment]
If you want the check box to be checked use 'default'=>'on'
This is what I do if I recall.

**Comment by roidayan** [comment]
Ha sorry its for multi check. Didn't notice. I use the one check box.

**Comment by hyyan** [comment]
@roidayan never mind , it is OK

**Comment by roidayan** [comment]
I checked your problem. the problem is the array_flip.
you get array like this:
array(
'key1' => 0,
'key2' => 1,
..
)

but the check being done is against the key name so you need this array:
array(
'key1' => 'key1',
'key2' => 'key2',
..
)

you can use the array_combine like you did for options.

**Comment by hyyan** [comment]
@roidayan You are totally write , I've changed to code to become like this : 

```php
$metas = array(....);
$fields['my-section-name'] = array();
foreach ($metas as $section => $values) {

$fields['my-section-name'][] = array(
        'name' => $section,
        'label' => $section,
        'type' => 'multicheck',
        'default' => array_combine($values,$values),
        'options' => array_combine(
                $values
                , $values
        )
    );
}
```

And it is working perfectly , thanks for the fast response .
