### ISSUE TITLE
Multicheck: unable to uncheck all boxes when defaults are set

### ISSUE THREAD

**Issue by factmaven** [tareq1988/wordpress-settings-api-class#63]
Right now I've set up a `multicheck` with defaults set like so:

```php
array(
    'name' => 'multi_slug',
    'label' => __( 'Multicheckboxes', 'example' ),
    'type' => 'multicheck',
    'default' => array(
        'option_2' => 'option_2',
        'option_3' => 'option_3',
    ),
    'options' => array(
        'option_1' => 'Option #1',
        'option_2' => 'Option #2',
        'option_3' => 'Option #3',
        'option_4' => 'Option #4',
    )
),
```

I am able to uncheck the checkboxes and save those changes. Yet, if I uncheck all of the checkboxes, it will revert back to having the default checkboxes (`option_2` and `option_3`) checked again.

Where can I fix that in the `class.settings-api.php`?

**Comment by factmaven** [comment]
@tareq1988 @roidayan Any recommendations?

**Comment by roidayan** [comment]
yes. need to add empty input to make sure the http post will send something. i'll add a pull request with the fix and you can take a look. tested with the example oop-example.php that is being loaded.

**Comment by factmaven** [comment]
@roidayan Thank you.
