### ISSUE TITLE
Save default values to the database upon activation

### ISSUE THREAD

**Issue by factmaven** [tareq1988/wordpress-settings-api-class#66]
I see here on ticket #27 where the default values are initialized in the `add_option` and saved in the database as soon as the class is called, such as when the plugin is first activated.

To me, this is very helpful since I want my plugin to immediately work upon activation with the default value that I've set and then let the user change these values themselves. I see this issue was brought up on #22, but it has been label as `wontfix`.

**Comment by roidayan** [comment]
There is no reason to fill the database with the defaults. get_option method will return the default if the option is not in the db.

**Comment by factmaven** [comment]
Hi @roidayan,

May you elaborate? Unfortunately I do not understand the process.

What I see right now is the options are checked or filled in with their default values, but none of them are set unless the user clicks "Save changes". For me, I want my default options saved so it can run the necessary functions based on the default values.

**Comment by roidayan** [comment]
As you said those are defaults. meaning if an option is not saved in the database then get_option() method will return the default. by saving default option to database get_option() will still return the same value but added unneeded info into the db.

**Comment by factmaven** [comment]
I see, thanks for clarifying.
