### ISSUE TITLE
What is the get_pages() function used for?

### ISSUE THREAD

**Issue by factmaven** [tareq1988/wordpress-settings-api-class#69]
In the [oop-example.php](https://github.com/tareq1988/wordpress-settings-api-class/blob/master/example/oop-example.php) file, what does the [`get_pages()`](https://github.com/tareq1988/wordpress-settings-api-class/blob/master/example/oop-example.php#L189) function do exactly?

```php
    function get_pages() {
        $pages = get_pages();
        $pages_options = array();
        if ( $pages ) {
            foreach ($pages as $page) {
                $pages_options[$page->ID] = $page->post_title;
            }
        }
        return $pages_options;
    }
```

Based on the comment code above it:

    /**
     * Get all the pages
     *
     * @return array page names with key value pairs
     */

Does this return multiple plugin page settings that are defined in [`admin_menu()`](https://github.com/tareq1988/wordpress-settings-api-class/blob/master/example/oop-example.php#L20)?

**Comment by roidayan** [comment]
doesn't seem to be in use. the function just seem to return ids and titles of pages in your blog.

**Comment by tareq1988** [comment]
It was used to generate a page dropdown in the settings area.

**Comment by factmaven** [comment]
@tareq1988 @roidayan 

So this function is no longer necessary then?
