### ISSUE TITLE
Only the active Tab fields saved, others don't

### ISSUE THREAD

**Issue by laranz** [tareq1988/wordpress-settings-api-class#84]
Just plan to try out how this is made, I found one issue,

1. Go to Settings page,
2. Make changes to the fields in both tabs,
3. Hit save,
4. Only the active tab fields saved, other tab's changes are ignored.

Regards,

**Comment by tareq1988** [comment]
This is how it works. Every tab is a separate form and saves separately.

**Comment by laranz** [comment]
Yes I know, in that case we don't need that animation when clicked, instead we need a full page reload. or simply a option to turn that off. Just my 2️⃣ 💵
